### ISSUE TITLE
Disabling binglog on load of ps_helper_56.sql

### ISSUE THREAD

**Issue by joegrasse** [MarkLeith/dbahelper#2]
Is there a reason you are disabling binlogs in the sql file? Seems like you would want this on all servers in a replication hierarchy.

**Comment by MarkLeith** [comment]
I took the principle of least surprise here, a lot of people _don't_ want admin scripts like this to replicate across the hierarchy. Changes to performance_schema tables themselves (the setup_\* tables) also do not replicate.
