### ISSUE TITLE
statement_analysis views have duplicate digests

### ISSUE THREAD

**Issue by aadant** [MarkLeith/dbahelper#5]
Due to a change in MySQL 5.6.9, 

"
This table was added in 5.6.5. Before MySQL 5.6.9, there is no SCHEMA_NAME column and grouping is based on DIGEST values only. 
"

http://dev.mysql.com/doc/refman/5.6/en/statement-summary-tables.html

there are duplicates in this view because the statements are groupped by 
(schema_name, digest).

So 2 possible solutions : 
1. add the schema name columns 
2. group by digest and aggregate the values

**Comment by MarkLeith** [comment]
Fixed with this merge https://github.com/MarkLeith/dbahelper/commit/500b9bf3895aeb710703b57058952f6db01f0f56.

Thanks Arnaud for the fix!
